#!/bin/bash
chmod +x /interface_setup
/interface_setup
ip rou del default 2> /dev/null
ip route add default via 10.161.0.254 dev net0
[ ! -e "/root/.ethereum/geth/nodekey" ] && geth --datadir /root/.ethereum init /tmp/eth-genesis.json
cp /tmp/keystore/UTC--2024-03-12T14-03-29.096831000Z--0x778e9e28A28326F2E8Def5910CE780c44329cCad /root/.ethereum/keystore/
cp /tmp/keystore/UTC--2024-03-12T14-03-30.102651000Z--0x48B4477F7A16D0b6D7a7c25546e28A3C29049E80 /root/.ethereum/keystore/
chmod +x /tmp/eth-bootstrapper
/tmp/eth-bootstrapper
geth --datadir /root/.ethereum --identity="NODE_14" --networkid=1337 --syncmode full --snapshot=False --verbosity=2 --allow-insecure-unlock --port 30303 --bootnodes "$(cat /tmp/eth-node-urls)" --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api web3,eth,debug,personal,net,clique,engine,admin,txpool --unlock "0x778e9e28A28326F2E8Def5910CE780c44329cCad, 0x48B4477F7A16D0b6D7a7c25546e28A3C29049E80" --password "/tmp/eth-password"                             &

echo "ready! run 'docker exec -it $HOSTNAME /bin/zsh' to attach to this node" >&2
for f in /proc/sys/net/ipv4/conf/*/rp_filter; do echo 0 > "$f"; done
tail -f /dev/null

