version: "3"

services:
    web-server:
        image: handsonsecurity/seed-server:padding-oracle
        container_name: oracle-10.9.0.80
        tty: true
        ports:                     # <-- Add this section
            - "6000:6000"          # Maps host:5000 → container:5000
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.80

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24